<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>LanguageCourseManagement.MVC</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<UserSecretsId>a3f7b2c1-8d4e-4f9a-b6c3-2e5d8a1f7c9b</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\LanguageCourseManagement.Application\LanguageCourseManagement.Application.csproj" />
		<ProjectReference Include="..\LanguageCourseManagement.Infrastructure\LanguageCourseManagement.Infrastructure.csproj" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="logs\" />
	</ItemGroup>

</Project>
